version: '3.7'

services:
  petclinic-api:
    image: serenitydojo/serenity-petclinic-api
    build:
      context: ./petclinic-api
      dockerfile: Dockerfile
    ports:
      - "9966:9966"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9966/petclinic/api/pets"]
      interval: 10s
      timeout: 5s
      retries: 3
#      start_period: 40s

  petclinic-ui:
    image: serenitydojo/serenity-petclinic-ui
    depends_on:
      - petclinic-api
    build:
      context: ./petclinic-ui
      dockerfile: Dockerfile
    ports:
      - "8080:80"