name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  start_app:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and launch the PetClinic app
#      working-directory: petclinic-api
      run: |
        docker-compose build
        docker-compose up -d
#        docker build . --file Dockerfile --tag serenitydojo/serenity-petclinic-api:$(date +%s)
#        docker run -p 9966:9966 --detach --name petclinic-api serenitydojo/serenity-petclinic-api:$(date +%s)
#
#  start_ui:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Build the PetClinic UI
#        working-directory: petclinic-ui
#        run: |
#          docker build . --file Dockerfile --tag serenitydojo/serenity-petclinic-ui:$(date +%s)
#          docker run -p 8080:80 --detach --name petclinic-ui serenitydojo/serenity-petclinic-ui:$(date +%s)

  acceptance_tests:
    needs: [start_app]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Start the PetClinic application
        working-directory: petclinic-ui
        run: mvn --version

